# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TradingExperts' do
  use_frameworks!

#  pod 'FacebookCore'
#  pod 'FacebookLogin'
#  pod 'FacebookShare'
#  pod 'Stripe'
#  pod 'Mobile-Buy-SDK'
#  pod 'Stripe'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'SimpleImageViewer'
  pod "youtube-ios-player-helper"
  pod 'SwiftyJSON'
end
